name: docker-build-and-push-self-hosted

on:
  push:
    tags:
      - openadkit-v*.*.*
  schedule:
    - cron: 0 0 1,15 * *
  workflow_dispatch:
    inputs:
      artifacts-destination:
        type: choice
        description: Destination for the artifacts
        options:
          - registry
          - tarball
        default: tarball

jobs:
  load-env:
    uses: ./.github/workflows/load-env.yaml

  docker-build-and-push:
    needs: load-env
    runs-on: [self-hosted, linux, ARM64]
    strategy:
      fail-fast: false
      matrix:
        name:
          - no-cuda
          - cuda
        include:
          - name: no-cuda
            platform: arm64
            base_image_env: base_image
            lib_dir: aarch64
            setup-args: --no-nvidia
            additional-tag-suffix: ""
          - name: cuda
            platform: arm64
            base_image_env: base_image
            lib_dir: aarch64
            additional-tag-suffix: -cuda
    steps:
      # https://github.com/actions/checkout/issues/211
      - name: Change permission of workspace
        run: |
          sudo chown -R $USER:$USER ${{ github.workspace }}

      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set git config
        uses: autowarefoundation/autoware-github-actions/set-git-config@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Free disk space
        uses: ./.github/actions/free-disk-space

      - name: Build 'Autoware'
        uses: ./.github/actions/docker-build-and-push
        with:
          name: ${{ matrix.name }}
          platform: ${{ matrix.platform }}
          bake-target: autoware
          build-args: |
            *.platform=linux/${{ matrix.platform }}
            *.args.ROS_DISTRO=${{ needs.load-env.outputs.rosdistro }}
            *.args.BASE_IMAGE=${{ needs.load-env.outputs[format('{0}', matrix.base_image_env)] }}
            *.args.SETUP_ARGS=${{ matrix.setup-args }}
            *.args.LIB_DIR=${{ matrix.lib_dir }}
            *.cache-from=type=registry,ref=ghcr.io/${{ github.repository }}-buildcache:${{ matrix.name }}-${{ matrix.platform }}-${{ github.ref_name }}
            *.cache-from=type=registry,ref=ghcr.io/${{ github.repository }}-buildcache:${{ matrix.name }}-${{ matrix.platform }}-main
            *.cache-to=type=registry,ref=ghcr.io/${{ github.repository }}-buildcache:${{ matrix.name }}-${{ matrix.platform }}-${{ github.ref_name }},mode=max
          tag-suffix: ${{ matrix.additional-tag-suffix }}-${{ matrix.platform }}
          tag-prefix: ${{ needs.load-env.outputs.rosdistro }}
          allow-push: true

      - name: Show disk space
        run: |
          df -h
